library(raster)
library(sf)
library(fasterize)
library(sp)
library(ranger)
library(terra)

Statechecklist <- readRDS('data/BONAPState2015.RDS')
Countychecklist <- readRDS('data/BONAPFips2015.RDS')
MexiStatechecklist <- read.delim('data/mexstaterecords.txt')
MexiStatelist <- read.delim('data/mexicanstates.txt', encoding = 'latin1')
MexiStatelist$State <- trimws(MexiStatelist$State)

states <- readRDS('data/states.RDS')
states.list <- st_drop_geometry(states)
states.list <- merge(states.list, MexiStatelist, by.x = 'STATE', by.y = 'State', all.x = T,  all.y = T)